server:
  port: 3000
spring:
  application:
    name: cloud-order-com.atguigu.springcloud.service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0到1之间，1表示全部采集
eureka:
  client:
    # 标识将自己注册进入eureka server中
    register-with-eureka: true
    fetch-registry: true # 从eurekaserver抓取已有的注册信息，默认为true，如果集群必须为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://eurekaa:7001/eureka/ # 入驻地址
      defaultZone: http://eurekaa:7001/eureka/,http://eurekab:7002/eureka/ # 入驻地址
  instance:
    lease-renewal-interval-in-seconds: 1 # Eureka客户端向服务端发送心跳的时间间隔，单位为秒，默认30
    lease-expiration-duration-in-seconds: 2 # 心跳最长等待时间上限，默认90，单位秒
