server:
  port: 7001

eureka:
  instance:
    hostname: eurekaa #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不像注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url: # 设置与eureka server交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://eurekaa:7001/eureka/ # 单机就是自己
#      defaultZone: http://eurekab:7002/eureka/ # 集群是其他注册中心
#  server:
#    enable-self-preservation: false # 关闭自我保护机制
#    eviction-interval-timer-in-ms: 2000