server:
  port: 3000

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaa:7001/eureka/ # 入驻地址

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


feign: #开启feign对hystrix的支持
  hystrix:
    enabled: true
